sources:
  - WeatherToday/Sources
templates:
  - tools/sourcery/templates
output:
  WeatherTodayTests/Sources/Mocks/Sourcery
args:
  autoMockableTestableImports:
    - WeatherToday
  autoMockableImports:
    - RxSwift
    - RxCocoa
