# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to Firebase"
  lane :increment_version do
    latest_release = firebase_app_distribution_get_latest_release(
      app: "1:999217461241:ios:7f30e2afa1e2f45e6f6f28"
    )
    increment_build_number({ build_number: latest_release[:buildVersion].to_i + 1 })
  end
  lane :release_to_firebase do
    build_app(
      workspace: "WeatherToday.xcworkspace",
      scheme: "WeatherToday",
      output_directory: "result",
      output_name: "WeatherToday",
      clean: true,
      export_method: "ad-hoc",
      xcargs: "-allowProvisioningUpdates"
    )
    firebase_app_distribution(
      app: "1:999217461241:ios:7f30e2afa1e2f45e6f6f28",
      firebase_cli_token: "1//0gwLWPD8CpWOyCgYIARAAGBASNwF-L9IrjIctiePEDs56A1DBUfomW3baDVIGyEg5e3mhBenTq-7aAgTPKBJ8Ep7XVHdWysJ2gQY",
      ipa_path: "result/WeatherToday.ipa",
      groups: "ci-cd-project-weather-today-testers",
      release_notes: "Lots of amazing new features to test out!"
  )
  end
end
